RIP_DZ_1/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('register/', views.AccountRegistrationView.as_view(), name='account_registration'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('get/<str:username>/', views.get_profile, name='get'),
    path('edit/', views.update_profile, name='edit')
]

RIP_DZ_1/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.ServicesListView.as_view(), name='list'),
    path('<int:pk>/<slug:slug>/', views.ServicesDetailView.as_view(), name='detail'),
    path('mine', views.MineOrders.as_view(), name='mine'),

    path('service/create/', views.CreateService.as_view(), name='create'),
    path('service/<int:pk>/edit', views.EditService.as_view(), name='edit'),
    path('service/<int:pk>/delete', views.DeleteService.as_view(), name='delete'),
]

RIP_DZ_1/homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RIP_DZ_1/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    {% block to_head %}{% endblock %}
    <link href="https://fonts.googleapis.com/css?family=PT+Sans+Narrow" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{% block title %}First Homework{% endblock %}</title>
</head>
<body style="background-color:grey">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav ml-auto">
                  <a class="nav-item nav-link" href="{% url 'account:login' %}">Войти</a>
                </div>
            </div>
        </div>
    </nav>
</header>

<main>
    {% block content %}{% endblock %}
</main>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="{% static 'js/waypointjs/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/waypointjs/lib/shortcuts/infinite.min.js' %}"></script>

{% block to_body %}{% endblock %}
</body>
</html>