RIP_DZ_1/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('register/', views.AccountRegistrationView.as_view(), name='account_registration'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('get/<str:username>/', views.get_profile, name='get'),
    path('edit/', views.update_profile, name='edit')
]

RIP_DZ_1/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.ServicesListView.as_view(), name='list'),
    path('<int:pk>/<slug:slug>/', views.ServicesDetailView.as_view(), name='detail'),
    path('mine', views.MineOrders.as_view(), name='mine'),

    path('service/create/', views.CreateService.as_view(), name='create'),
    path('service/<int:pk>/edit', views.EditService.as_view(), name='edit'),
    path('service/<int:pk>/delete', views.DeleteService.as_view(), name='delete'),
]

RIP_DZ_1/homework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RIP_DZ_1/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.validators import MinValueValidator



class Service(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    slug = models.SlugField(max_length=200, verbose_name='Слаг', db_index=True)
    description = models.TextField(blank=True, verbose_name='Описание услуги')
    photo = models.ImageField(default='../static/images/not_found.jpg',
                              upload_to='services/%Y',
                              verbose_name='Картинка услуги')
    customer = models.ForeignKey(User,
                                 related_name='service_created',
                                 on_delete=models.CASCADE,
                                 verbose_name='Заказчик услуги')
    bids = models.ManyToManyField(User,
                                  related_name='service_bid',
                                  blank=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    active = models.BooleanField(default=True, blank=False, verbose_name='Услуга активна')

    class Meta:
        ordering = ('-updated',)
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return "{} {}".format(self.name, self.customer)

    def get_absolute_url(self):
        return reverse('core:detail', args=[self.id, self.slug])

RIP_DZ_1/core/forms.py
from django import forms
from django.forms import ModelForm
from .models import Service
from django.contrib.auth.models import User


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'description', 'photo', 'active']

RIP_DZ_1/core/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views.generic.base import TemplateResponseMixin, View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Service
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ServiceForm
from django.shortcuts import get_object_or_404
from django.views.generic.edit import FormView
from django.template.defaultfilters import slugify
from unidecode import unidecode
from django.urls import reverse_lazy, reverse
from braces.views import CsrfExemptMixin, JsonRequestResponseMixin
from django.core.exceptions import ValidationError
from django.http import Http404


class ServiceModelMixin(object):
    model = Service

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(active=True)

    template_name = 'core/list.html'


class ServiceOwnerMixin(object):
    model = Service
    template_name = 'core/mine.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(customer=self.request.user)


class ServicesListView(LoginRequiredMixin, ServiceModelMixin, ListView):
    paginate_by = 5


class ServicesDetailView(ServiceModelMixin, CsrfExemptMixin, JsonRequestResponseMixin, DetailView):
    template_name = 'core/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)

        if self.object.customer == self.request.user:
            context['is_owner'] = 1
            context['list_customers'] = self.object.bids.all()
        else:
            context['is_in_list'] = 1 if self.request.user in self.object.bids.all() else 0
        return context

    def post(self, request, *args, **kwargs):
        self.get_object().bids.add(request.user)
        return redirect(reverse_lazy('core:detail',
                                     kwargs={'pk': self.get_object().id,
                                             'slug': self.get_object().slug}))


class MineOrders(LoginRequiredMixin, ServiceOwnerMixin, ListView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        context['form'] = ServiceForm
        return context


class CreateService(CsrfExemptMixin, JsonRequestResponseMixin, CreateView):
    form_class = ServiceForm
    success_url = reverse_lazy('core:mine')

    def get(self, request, *args, **kwargs):
        try:
            super().get(args, kwargs)
        except:
            return redirect(reverse_lazy('core:mine'))

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.customer = self.request.user
            form.instance.slug = slugify(unidecode(form.instance.name))

            return super().form_valid(form)
        return redirect(reverse_lazy('account:login'))


class EditService(LoginRequiredMixin, UpdateView):
    model = Service
    success_url = reverse_lazy('core:mine')
    template_name = 'core/edit.html'
    form_class = ServiceForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.slug = slugify(unidecode(form.instance.name))

            return super().form_valid(form)
        return redirect(reverse_lazy('account:login'))


class DeleteService(LoginRequiredMixin, DeleteView):
    model = Service
    success_url = reverse_lazy('core:mine')

    def get_object(self, queryset=None):
        obj = super().get_object()
        if not obj.customer == self.request.user:
            raise Http404
        return obj

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

RIP_DZ_1/core/templates/core/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {{ object.name }}
{% endblock %}

{% block content %}
    <div class="container detail-content_block">
        <h1>{{ object.name }}</h1>
        <p class="text-muted" style="font-size: 25px;">
            Сделал ставку:
            <a href="{% url 'account:get'  object.customer.username %}">{{ object.customer.username }}</a>.
            Последнее изменение: {{ object.updated }}
        </p>
        <div class="row mt-3">
            <div class="col-lg-6">
                <img src="{{ object.photo.url }}" alt="" style="width: 100%;">
            </div>
            <div class="col-lg-6">
                <h3 class="mt-0 mt-xs-5 ">Данные о ставке:</h3>
                <p>{{ object.description }}</p>
            </div>
        </div>
        <div class="customers_list mt-3">
            {% if list_customers %}
                <h3>Принял ставку:</h3>
                <ul>
                    {% for i in list_customers %}
                        <li><a href="{% url 'account:get' i.username %}">{{ i.username }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                {% if is_owner %}
                    <h3>Вашу ставку еще не приняли</h3>
                {% else %}
                    {% if request.user.is_authenticated %}
                        {% if is_in_list %}
                            <p class="text-center mt-4">Вы уже делали ставку</p>
                        {% else %}
                            <div class="respond_block text-center mt-4">
                                <form action="." method="post" id="respond_form">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-success">Принять ставку</button>
                                </form>
                            </div>
                        {% endif %}
                    {% else %}
                        <p class="text-center mt-4">Авторизируйтесь на сайте, чтобы сделать ставку</p>
                    {% endif %}
                {% endif %}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block to_body %}
    <script src="{% static 'js/enroll_w_reload.js' %}" type="text/javascript"></script>
{% endblock %}

RIP_DZ_1/core/templates/core/edit.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}
    Изменение {{ object.name }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="update-form">
            <form action="{% url 'core:edit' object.id %}" method="post" id="create-update"
                  enctype="multipart/form-data">
                {{ form|bootstrap }}
                {% csrf_token %}
                <p class="text-center"><input class="btn btn-outline-info" type="submit" value="Применить"></p>
            </form>
        </div>
    </div>
{% endblock %}

RIP_DZ_1/core/templates/core/list.html
{% extends "base.html" %}

{% block title %}
    Все ставки
{% endblock %}

{% block content %}
    <div class="container my-5 infinite-container">
        {% for i in object_list %}
            <div class="infinite-item">
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <a href="{{ i.get_absolute_url }}">
                            <img src="{{ i.photo.url }}" alt="" class="img-thumbnail list_image">
                        </a>
                    </div>
                    <div class="col-lg-8 col-sm-6 list_info">
                        <a href="{{ i.get_absolute_url }}">{{ i.name }}</a>
                        <p class="text-muted">{{ i.customer.username }}</p>
                    </div>
                </div>
                <hr>
            </div>
        {% endfor %}
    </div>

    <div class="loading" style="text-align: center;display: none;">
        Loading...
    </div>
    {% if page_obj.has_next %}
        <a class="infinite-more-link d-none" href="?page={{ page_obj.next_page_number }}">More</a>
    {% endif %}
{% endblock %}

{% block to_body %}
    <script>
        let infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
                $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
                $('.loading').hide();
            }
        });
    </script>
{% endblock %}

RIP_DZ_1/core/templates/core/mine.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}
    Мои ставки
{% endblock %}

{% block content %}
    <div class="container my-5">
        <div class="create_service">
            <div class="create_service__firstbutton">
                <button type="button" id='create_service__button' class="btn btn-primary" data-toggle="modal"
                        data-target="#exampleModal">
                    +
                </button>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Добавление ставки</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <form id='create_form__form' action="{% url 'core:create' %}" method="POST"
                              enctype='multipart/form-data'>
                            {% csrf_token %}
                            <div class="modal-body">
                                {{ form|bootstrap }}
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-primary">Применить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% for i in object_list %}
            <div class="row">
                <div class="col-lg-4 col-sm-6">
                    <a href="{{ i.get_absolute_url }}">
                        <img src="{{ i.photo.url }}" alt="" class="img-thumbnail list_image">
                    </a>
                </div>
                <div class="col-lg-8 col-sm-6 list_info">
                    <a href="{{ i.get_absolute_url }}">{{ i.name }}</a>
                    <p class="text-muted">{{ i.customer.username }}</p>
                    <a href="{% url 'core:delete' i.id %}">Удалить</a>
                    <a href="{% url 'core:edit' i.id %}">Изменить</a>
                </div>
            </div>
            <hr>
        {% empty %}
            Вы еще не делали ставки на сайте!
        {% endfor %}
    </div>
{% endblock %}


{% block to_body %}
    <script>
        $(document).ready(function () {
            $('#id_price').attr('min', 0);
            {#$('#id_description').attr('cols', '40');#}
        });
    </script>
{% endblock %}